# Generated by Django 2.2.12 on 2020-06-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('book_type', models.CharField(max_length=200)),
                ('reviews_count', models.IntegerField()),
                ('price', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('cover_img', models.FileField(upload_to='')),
            ],
        ),
    ]
