# Generated by Django 2.2.12 on 2020-06-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.CharField(max_length=1000),
        ),
    ]
